// <auto-generated />
using System;
using System.Reflection;
using System.Resources;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("LegoGif")]
[assembly: AssemblyDescription("")]
[assembly: Guid("f40b1a7c-4800-4bc9-9614-32b46949ca86")]
[assembly: NeutralResourcesLanguage("en-US")]
[assembly: CLSCompliant(true)]
